name: CI for Java using GithubActions
on:
 push:
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Clone the git repository
     uses: actions/checkout@v4
   - name : Install dependent packages
     run : | 
      sudo apt update
      sudo apt install -y openjdk-17-jdk
      sudo apt install -y maven
   - name: Compile using maven
     run: mvn clean install -f Javarepo1/pom.xml
   - name: Upload Jar
     uses: actions/upload-artifact@v4
     with:
      name: my-java-application
      path: Javarepo1/target/*.jar
